### ISSUE TITLE
japanese encoded zip filename is garbled (probably) 

### ISSUE THREAD

**Issue by yukihane** [yukihane/scoop#1]
https://github.com/lukesampson/scoop/pull/2577#issuecomment-419711984
の調査が必要。

予想では、ファイル名が [`CP 932`](https://en.wikipedia.org/wiki/Code_page_932_(Microsoft_Windows))(Shift_JIS) でエンコードされているのではないか。

https://github.com/lukesampson/scoop/blob/9bc7d5f8b3ded507cd5d631fce189e88f562042a/lib/core.ps1#L267
で `ZipFile::ExtractToDirectroy` を使用しているが、ここで [`entryNameEncoding` を指定する](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.extracttodirectory?view=netframework-4.7.2#System_IO_Compression_ZipFile_ExtractToDirectory_System_String_System_String_System_Text_Encoding_)必要があるのかもしれない。

Windows7/Windows Server 2008 R2 であれば、次の問題の可能性も？
https://support.microsoft.com/en-us/help/2704299/japanese-characters-in-file-names-are-displayed-as-garbled-text-after

**Comment by yukihane** [comment]
元issueにも記載したが、

* zipファイル名エンコードについては上記の通り `entryNameEncoding` を明示することで解消

ただし、この問題を解消した後また別の問題が発生した。(ショートカット作成)

**Comment by sayurin** [comment]
SOからやってきました。
このプログラムは日本語専用なのでしょうか？ そうでないのであれば、[SOで回答](https://ja.stackoverflow.com/a/48262/4236)したようにプログラム実行者が適切な言語設定を行うべきかと思います。zipファイル内のファイル名のエンコーディング解釈も適切に行えますし、ショートカットも適切に行われます。

逆に`Shift-JIS`でハードコーディングしてしまうと、非SJIS文字が設定されている場合にファイル名が文字化けします。例えば英語文書で`'`とは少し字形の異なるアポストロフィを見かけたり、もしくはアポストロフィだけが文字化けしている文書を目にしたことはありませんか？ これはShift-JIS以外のエンコーディングが利用されているからです。

**Comment by yukihane** [comment]
@sayurin さん。コメントありがとうございます。

これまでに残している文書は、自分が忘れないように書き散らしたメモだったり、文法のあやしい英語だったりというものだけなので、ここでは、一度、現時点での私の考えをまとめたものを記載したいと思います。

----

現時点で私が認識している問題は3点あり、これらは大きく2種に分類できると考えております。

* **問題分類A**: 自国語環境で自国語を取り扱う場合でも発現する問題(ただしASCII文字の範囲では正常動作する)
  * **問題A1**: 設定ファイル(注)が特定の処理フロー中でUTF-8エンコーディングで扱われず、非ASCII文字を含んでいると正常に読み取られない。
* **問題分類B**: 自国語環境で他国語を取り扱う場合に発現する問題
  * **問題B1**: 処理対象zipアーカイブ内に非ASCII文字で命名されたファイルがあると展開時文字化けする。
  * **問題B2**: 非ASCII文字のショートカットを作成しようとするとエラーとなる。

注: このアプリでは[App Manifests](https://github.com/lukesampson/scoop/wiki/App-Manifests)と呼称しているJSONフォーマットのファイル。

そして、直近、私が目指しているのは以下の事項です。

* **問題分類A** を解消したい。そのためには **問題A1** を解消すれば十分であることを示したい。 
* **問題B1** (及び **問題B2** )は別の原因によるものであり、**問題A1**とは独立していることを示したい。
* **問題分類B** を解消することに私は興味はない(そもそもまず解消すべき問題なのかどうか原作者が判断する必要があると考える。レアケースだと思うので)。

---

経緯説明:

上記問題のうち、当初私が発見したのは**問題A1**( https://github.com/lukesampson/scoop/issues/2573 )です。
原因としては、`WebClient`を利用してApp Manifestsを取得している処理でエンコーディングが明示されていないため、[`Default`エンコーディング](https://msdn.microsoft.com/ja-jp/library/system.net.webclient.encoding(v=vs.110).aspx)(私の環境ではShift_JIS)が採用されてしまっているのだろう、ということでこれを解消すべく[Pull Request #2577 set WebClient encoding to UTF-8 explicitly](https://github.com/lukesampson/scoop/pull/2577/files) を起票しました。

[JSONファイル仕様](https://tools.ietf.org/html/rfc8259#section-8.1)としてUTF-8は妥当で、かつ、本アプリケーション実装においてもApp Manifestsは[明示的にUTF-8である](https://github.com/lukesampson/scoop/search?q=UTF8&unscoped_q=UTF8)として扱っているように見えたので、このPull Requestは妥当であると考えています。

また、この修正を行うことによって、**私の環境では**想定通り動作完了するようになりました。

ただし、非日本語環境で実行すると問題が発生したようです( https://github.com/lukesampson/scoop/pull/2577#issuecomment-419711984 )。
調査した結果、 **問題A1** とは無関係の、zipファイル名エンコードの問題があることが分かりました(**問題B1**))。そこで、他国語を含む場合はエンコーディングの明示が必要であること、今回の場合は"shift-jis"を指定すればよいことを[返信しました](https://github.com/lukesampson/scoop/pull/2577#issuecomment-419929983)。

また、**問題B1**調査過程で、ショートカット作成処理においても他国語を処理しようとした場合には問題が発生することが分かりましたのでそちらについても同時に記載しました(**問題B2**)。

この際、**問題B2**については、「じゃあどうすれば直るの？」という指針も思い浮かばなかったので、[スタックオーバーフローで質問を行った](https://ja.stackoverflow.com/q/48260/2808)、という次第です。

**Comment by yukihane** [comment]
> 逆にShift-JISでハードコーディングしてしまうと、非SJIS文字が設定されている場合にファイル名が文字化けします。

私が[こちら](https://github.com/lukesampson/scoop/pull/2577#issuecomment-419929983)に記載したdiffに関してのコメントかと考えます。

上記のdiffについては、「その問題(**問題B1**)は今回のPull Requestの件(**問題A1**)とは別件である」というのを説明したかっただけで、このように修正すべき、ということを言いたかったわけではないのです…

**問題B1**を実際に対応するのであれば、おそらく、App Manifestsに設定項目を追加し、zip圧縮時に用いた文字エンコーディングの指定ができるようにすることになるのかな、と考えています。
…ということで、修正方法の方向性に @sayurin さんと相違は無いのかな、と思っております。

**問題B1**, **問題B2** はそれぞれ別にIssueを立てようと考えておりまして、その際に修正すべき問題か否か、修正する場合どう修正するのが正しいのか、について議論することになるかと。

**Comment by sayurin** [comment]
説明ありがとうございます。真に解決したいのは **問題A1** でありしかも解決済み、 **問題B1** **問題B2** は傍流である点、理解しました。

**Comment by yukihane** [comment]
#3 で3点の問題を別々のissueとして立てたのでcloseする。
